includes:
  - base.yaml
atta:
  name: SimATTA
  episodic: False
  budgets: 100
  batch_size: 100
  SimATTA:
    steps: 100
    lr: 1e-3
    eh: 1e-2
    el: 1e-3
    cold_start: 100
    nc_increase: 1
    stop_tol: 5
    target_cluster: 1
    LE: 1
num_workers: 8


